implement connection test

diff --git a/.ddev/commands/web/pull-wp b/.ddev/commands/web/pull-wp
--- a/.ddev/commands/web/pull-wp
+++ b/.ddev/commands/web/pull-wp
@@ -65,7 +65,29 @@ if [[ $UPDRAFT_CLI_ACTIVATED == "yes" ]]
         echo "Please enter yes or no, aborting."
         exit 1
     fi
+fi
 
+# checking ssh connection
+echo "Checking ssh connection and path ..."
+echo "Please provide the SSH password (use SSH keys to avoid this prompt):"
+if [ -n "$(ssh "${SSH_USER_HOST}" [ -d "${SSH_WORDPRESS_PATH}" ] && echo 1; exit)" ]; then
+    # exists
+    echo "Connection test passed ..."
+else
+    # doesn't exist
+    echo "Connection test failed, aborting."
+    exit 1
+fi
+
+# get remote wordpress version, save it as var
+# updraftplus free / standard version does not backup wpcore files
+echo "Getting the wpcore version information from remote site ..."
+echo "Please provide the SSH password (use SSH keys to avoid this prompt):"
+WP_CORE_VERSION_LIVE_WEBSITE=`ssh ${SSH_USER_HOST} wp core version --path=${SSH_WORDPRESS_PATH}`
+echo "Live website has version: ${WP_CORE_VERSION_LIVE_WEBSITE}"
+
+if [[ $UPDRAFT_CLI_ACTIVATED == "yes" ]]
+  then
     if [[ $CREATE_BACKUP_ON_REMOTE == "yes" ]]
       then
         echo "Create backup on remote storage via SSH..."
@@ -78,16 +100,15 @@ if [[ $UPDRAFT_CLI_ACTIVATED == "yes" ]]
         echo "Please provide the SSH password (use SSH keys to avoid this prompt):"
         UPDRAFT_TERMINAL_OUTPUT=`ssh ${SSH_USER_HOST} wp updraftplus get_latest_full_backup --path=${SSH_WORDPRESS_PATH}`
     fi
-
+    
     # we strip identifier from string after last : character
     # (Output will be something like: Success: Latest full backup found identifier: a7cfeXXXXc281)
     UPDRAFT_NONCE=${UPDRAFT_TERMINAL_OUTPUT##*: }
     # TODO: Error handling - check if nonce contains numbers/characters? check format?
     echo "Updraft nonce on remote is ${UPDRAFT_NONCE}"
-
-  # No updratfplus CLI on remote activated
+  # No updratfplus CLI on remote activated, just set it to empty string
   else
-    UPDRAFT_NONCE=""
+    UPDRAFT_NONCE=""  
 fi
 
 echo "Sync backup files from remote server to local DDEV (rsync) ..."
@@ -103,12 +124,7 @@ if [[ $UPDRAFT_NONCE != "" ]]
     rsync --archive --human-readable --rsh ssh --progress --include="*.zip" --include="*.gz" --exclude="*" ${SSH_USER_HOST}:${SSH_WORDPRESS_PATH}/wp-content/updraft/ wp-content/updraft/
 fi
 
-# get remote wordpress version, save it as var
-# updraftplus free / standard version does not backup wpcore files
-echo "Getting the wpcore version information from remote site ..."
-echo "Please provide the SSH password (use SSH keys to avoid this prompt):"
-WP_CORE_VERSION_LIVE_WEBSITE=`ssh ${SSH_USER_HOST} wp core version --path=${SSH_WORDPRESS_PATH}`
-echo "Live website has version: ${WP_CORE_VERSION_LIVE_WEBSITE}"
+
 
 # TODO: if core version is the same, don't change it
 
